name: CI - Test du site

on:
  push:
    branches:
      - main

jobs:
  test-site:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Vérification du fichier index.html
        run: |
          echo "Début des tests"
          test -f index_fake.html
          echo "Le fichier index.html est présent"
